"""add_medical_appointments_and_conversations

Revision ID: 0587e6432416
Revises: b7c4e91a2f63
Create Date: 2026-08-24 07:32:21.084372

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0587e6432416'
down_revision: Union[str, Sequence[str], None] = 'b7c4e91a2f63'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('medical_appointments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('doctor_id', sa.Integer(), nullable=False),
    sa.Column('appointment_date', sa.Date(), nullable=False),
    sa.Column('appointment_time', sa.Time(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['doctor_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['patient_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_medical_appointments_appointment_date'), 'medical_appointments', ['appointment_date'], unique=False)
    op.create_index(op.f('ix_medical_appointments_appointment_time'), 'medical_appointments', ['appointment_time'], unique=False)
    op.create_index(op.f('ix_medical_appointments_doctor_id'), 'medical_appointments', ['doctor_id'], unique=False)
    op.create_index(op.f('ix_medical_appointments_id'), 'medical_appointments', ['id'], unique=False)
    op.create_index(op.f('ix_medical_appointments_patient_id'), 'medical_appointments', ['patient_id'], unique=False)
    op.create_index(op.f('ix_medical_appointments_status'), 'medical_appointments', ['status'], unique=False)
    op.create_table('medical_doctor_availabilities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('doctor_id', sa.Integer(), nullable=False),
    sa.Column('day_of_week', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('slot_duration', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['doctor_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_medical_doctor_availabilities_day_of_week'), 'medical_doctor_availabilities', ['day_of_week'], unique=False)
    op.create_index(op.f('ix_medical_doctor_availabilities_doctor_id'), 'medical_doctor_availabilities', ['doctor_id'], unique=False)
    op.create_index(op.f('ix_medical_doctor_availabilities_id'), 'medical_doctor_availabilities', ['id'], unique=False)
    op.create_table('medical_doctor_availability_exceptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('doctor_id', sa.Integer(), nullable=False),
    sa.Column('exception_date', sa.Date(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=True),
    sa.Column('end_time', sa.Time(), nullable=True),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['doctor_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_medical_doctor_availability_exceptions_doctor_id'), 'medical_doctor_availability_exceptions', ['doctor_id'], unique=False)
    op.create_index(op.f('ix_medical_doctor_availability_exceptions_exception_date'), 'medical_doctor_availability_exceptions', ['exception_date'], unique=False)
    op.create_index(op.f('ix_medical_doctor_availability_exceptions_id'), 'medical_doctor_availability_exceptions', ['id'], unique=False)
    op.create_table('medical_appointment_status_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('appointment_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('changed_by', sa.Integer(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['appointment_id'], ['medical_appointments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['changed_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_medical_appointment_status_history_appointment_id'), 'medical_appointment_status_history', ['appointment_id'], unique=False)
    op.create_index(op.f('ix_medical_appointment_status_history_changed_by'), 'medical_appointment_status_history', ['changed_by'], unique=False)
    op.create_index(op.f('ix_medical_appointment_status_history_id'), 'medical_appointment_status_history', ['id'], unique=False)
    op.create_index(op.f('ix_medical_conversations_id'), 'medical_conversations', ['id'], unique=False)
    op.create_index(op.f('ix_medical_messages_id'), 'medical_messages', ['id'], unique=False)
    op.create_index(op.f('ix_medical_messages_notifications_id'), 'medical_messages_notifications', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_medical_messages_notifications_id'), table_name='medical_messages_notifications')
    op.drop_index(op.f('ix_medical_messages_id'), table_name='medical_messages')
    op.drop_index(op.f('ix_medical_conversations_id'), table_name='medical_conversations')
    op.drop_index(op.f('ix_medical_appointment_status_history_id'), table_name='medical_appointment_status_history')
    op.drop_index(op.f('ix_medical_appointment_status_history_changed_by'), table_name='medical_appointment_status_history')
    op.drop_index(op.f('ix_medical_appointment_status_history_appointment_id'), table_name='medical_appointment_status_history')
    op.drop_table('medical_appointment_status_history')
    op.drop_index(op.f('ix_medical_doctor_availability_exceptions_id'), table_name='medical_doctor_availability_exceptions')
    op.drop_index(op.f('ix_medical_doctor_availability_exceptions_exception_date'), table_name='medical_doctor_availability_exceptions')
    op.drop_index(op.f('ix_medical_doctor_availability_exceptions_doctor_id'), table_name='medical_doctor_availability_exceptions')
    op.drop_table('medical_doctor_availability_exceptions')
    op.drop_index(op.f('ix_medical_doctor_availabilities_id'), table_name='medical_doctor_availabilities')
    op.drop_index(op.f('ix_medical_doctor_availabilities_doctor_id'), table_name='medical_doctor_availabilities')
    op.drop_index(op.f('ix_medical_doctor_availabilities_day_of_week'), table_name='medical_doctor_availabilities')
    op.drop_table('medical_doctor_availabilities')
    op.drop_index(op.f('ix_medical_appointments_status'), table_name='medical_appointments')
    op.drop_index(op.f('ix_medical_appointments_patient_id'), table_name='medical_appointments')
    op.drop_index(op.f('ix_medical_appointments_id'), table_name='medical_appointments')
    op.drop_index(op.f('ix_medical_appointments_doctor_id'), table_name='medical_appointments')
    op.drop_index(op.f('ix_medical_appointments_appointment_time'), table_name='medical_appointments')
    op.drop_index(op.f('ix_medical_appointments_appointment_date'), table_name='medical_appointments')
    op.drop_table('medical_appointments')
    # ### end Alembic commands ###
