"""add start_date and end_date to availability

Revision ID: 0a3765c884c7
Revises: c91f4a72d8e1
Create Date: 2026-08-25 19:50:36.325110

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0a3765c884c7'
down_revision: Union[str, Sequence[str], None] = 'c91f4a72d8e1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('medical_doctor_availabilities', sa.Column('start_date', sa.Date(), nullable=True))
    op.add_column('medical_doctor_availabilities', sa.Column('end_date', sa.Date(), nullable=True))
    op.alter_column('medical_doctor_availabilities', 'day_of_week',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_index(op.f('ix_medical_doctor_availabilities_end_date'), 'medical_doctor_availabilities', ['end_date'], unique=False)
    op.create_index(op.f('ix_medical_doctor_availabilities_start_date'), 'medical_doctor_availabilities', ['start_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_medical_doctor_availabilities_start_date'), table_name='medical_doctor_availabilities')
    op.drop_index(op.f('ix_medical_doctor_availabilities_end_date'), table_name='medical_doctor_availabilities')
    op.alter_column('medical_doctor_availabilities', 'day_of_week',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('medical_doctor_availabilities', 'end_date')
    op.drop_column('medical_doctor_availabilities', 'start_date')
    # ### end Alembic commands ###
