"""create specialties and patient pathologies

Revision ID: 4e0d91e363e0
Revises: b9dddb76d364
Create Date: 2026-08-17 13:40:33.356946

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4e0d91e363e0'
down_revision: Union[str, Sequence[str], None] = 'b9dddb76d364'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pathologies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=150), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pathologies_category'), 'pathologies', ['category'], unique=False)
    op.create_index(op.f('ix_pathologies_code'), 'pathologies', ['code'], unique=True)
    op.create_index(op.f('ix_pathologies_id'), 'pathologies', ['id'], unique=False)
    op.create_index(op.f('ix_pathologies_name'), 'pathologies', ['name'], unique=False)
    op.create_table('specialties',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_specialties_id'), 'specialties', ['id'], unique=False)
    op.create_index(op.f('ix_specialties_name'), 'specialties', ['name'], unique=True)
    op.create_table('doctor_specialties',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('doctor_id', sa.Integer(), nullable=False),
    sa.Column('specialty_id', sa.Integer(), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctors.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['specialty_id'], ['specialties.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('doctor_id', 'specialty_id', name='uq_doctor_specialty')
    )
    op.create_index(op.f('ix_doctor_specialties_doctor_id'), 'doctor_specialties', ['doctor_id'], unique=False)
    op.create_index(op.f('ix_doctor_specialties_id'), 'doctor_specialties', ['id'], unique=False)
    op.create_index(op.f('ix_doctor_specialties_specialty_id'), 'doctor_specialties', ['specialty_id'], unique=False)
    op.create_table('patient_pathologies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('pathology_id', sa.Integer(), nullable=False),
    sa.Column('diagnosis_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['pathology_id'], ['pathologies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('patient_id', 'pathology_id', name='uq_patient_pathology')
    )
    op.create_index(op.f('ix_patient_pathologies_id'), 'patient_pathologies', ['id'], unique=False)
    op.create_index(op.f('ix_patient_pathologies_pathology_id'), 'patient_pathologies', ['pathology_id'], unique=False)
    op.create_index(op.f('ix_patient_pathologies_patient_id'), 'patient_pathologies', ['patient_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_patient_pathologies_patient_id'), table_name='patient_pathologies')
    op.drop_index(op.f('ix_patient_pathologies_pathology_id'), table_name='patient_pathologies')
    op.drop_index(op.f('ix_patient_pathologies_id'), table_name='patient_pathologies')
    op.drop_table('patient_pathologies')
    op.drop_index(op.f('ix_doctor_specialties_specialty_id'), table_name='doctor_specialties')
    op.drop_index(op.f('ix_doctor_specialties_id'), table_name='doctor_specialties')
    op.drop_index(op.f('ix_doctor_specialties_doctor_id'), table_name='doctor_specialties')
    op.drop_table('doctor_specialties')
    op.drop_index(op.f('ix_specialties_name'), table_name='specialties')
    op.drop_index(op.f('ix_specialties_id'), table_name='specialties')
    op.drop_table('specialties')
    op.drop_index(op.f('ix_pathologies_name'), table_name='pathologies')
    op.drop_index(op.f('ix_pathologies_id'), table_name='pathologies')
    op.drop_index(op.f('ix_pathologies_code'), table_name='pathologies')
    op.drop_index(op.f('ix_pathologies_category'), table_name='pathologies')
    op.drop_table('pathologies')
    # ### end Alembic commands ###
