"""create medical sources queries and responses

Revision ID: 66dae21f88c0
Revises: 4e0d91e363e0
Create Date: 2026-08-17 14:15:13.371444

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '66dae21f88c0'
down_revision: Union[str, Sequence[str], None] = '4e0d91e363e0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('medical_sources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('base_url', sa.String(length=500), nullable=True),
    sa.Column('api_url', sa.String(length=500), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_medical_sources_id'), 'medical_sources', ['id'], unique=False)
    op.create_index(op.f('ix_medical_sources_name'), 'medical_sources', ['name'], unique=True)
    op.create_index(op.f('ix_medical_sources_type'), 'medical_sources', ['type'], unique=False)
    op.create_table('medical_documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('external_id', sa.String(length=255), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('abstract', sa.Text(), nullable=True),
    sa.Column('url', sa.String(length=1000), nullable=True),
    sa.Column('publication_date', sa.Date(), nullable=True),
    sa.Column('authors', sa.Text(), nullable=True),
    sa.Column('document_type', sa.String(length=100), nullable=True),
    sa.Column('language', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['medical_sources.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_medical_documents_external_id'), 'medical_documents', ['external_id'], unique=False)
    op.create_index(op.f('ix_medical_documents_id'), 'medical_documents', ['id'], unique=False)
    op.create_index(op.f('ix_medical_documents_source_id'), 'medical_documents', ['source_id'], unique=False)
    op.create_table('medical_queries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('query', sa.Text(), nullable=False),
    sa.Column('query_type', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_medical_queries_id'), 'medical_queries', ['id'], unique=False)
    op.create_index(op.f('ix_medical_queries_patient_id'), 'medical_queries', ['patient_id'], unique=False)
    op.create_index(op.f('ix_medical_queries_query_type'), 'medical_queries', ['query_type'], unique=False)
    op.create_index(op.f('ix_medical_queries_status'), 'medical_queries', ['status'], unique=False)
    op.create_table('medical_query_pathologies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('query_id', sa.Integer(), nullable=False),
    sa.Column('pathology_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['pathology_id'], ['pathologies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['query_id'], ['medical_queries.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('query_id', 'pathology_id', name='uq_medical_query_pathology')
    )
    op.create_index(op.f('ix_medical_query_pathologies_id'), 'medical_query_pathologies', ['id'], unique=False)
    op.create_index(op.f('ix_medical_query_pathologies_pathology_id'), 'medical_query_pathologies', ['pathology_id'], unique=False)
    op.create_index(op.f('ix_medical_query_pathologies_query_id'), 'medical_query_pathologies', ['query_id'], unique=False)
    op.create_table('medical_query_sources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('query_id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('relevance_score', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['medical_documents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['query_id'], ['medical_queries.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_medical_query_sources_document_id'), 'medical_query_sources', ['document_id'], unique=False)
    op.create_index(op.f('ix_medical_query_sources_id'), 'medical_query_sources', ['id'], unique=False)
    op.create_index(op.f('ix_medical_query_sources_query_id'), 'medical_query_sources', ['query_id'], unique=False)
    op.create_table('medical_responses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('query_id', sa.Integer(), nullable=False),
    sa.Column('response', sa.Text(), nullable=False),
    sa.Column('model', sa.String(length=100), nullable=False),
    sa.Column('prompt_version', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['query_id'], ['medical_queries.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_medical_responses_id'), 'medical_responses', ['id'], unique=False)
    op.create_index(op.f('ix_medical_responses_query_id'), 'medical_responses', ['query_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_medical_responses_query_id'), table_name='medical_responses')
    op.drop_index(op.f('ix_medical_responses_id'), table_name='medical_responses')
    op.drop_table('medical_responses')
    op.drop_index(op.f('ix_medical_query_sources_query_id'), table_name='medical_query_sources')
    op.drop_index(op.f('ix_medical_query_sources_id'), table_name='medical_query_sources')
    op.drop_index(op.f('ix_medical_query_sources_document_id'), table_name='medical_query_sources')
    op.drop_table('medical_query_sources')
    op.drop_index(op.f('ix_medical_query_pathologies_query_id'), table_name='medical_query_pathologies')
    op.drop_index(op.f('ix_medical_query_pathologies_pathology_id'), table_name='medical_query_pathologies')
    op.drop_index(op.f('ix_medical_query_pathologies_id'), table_name='medical_query_pathologies')
    op.drop_table('medical_query_pathologies')
    op.drop_index(op.f('ix_medical_queries_status'), table_name='medical_queries')
    op.drop_index(op.f('ix_medical_queries_query_type'), table_name='medical_queries')
    op.drop_index(op.f('ix_medical_queries_patient_id'), table_name='medical_queries')
    op.drop_index(op.f('ix_medical_queries_id'), table_name='medical_queries')
    op.drop_table('medical_queries')
    op.drop_index(op.f('ix_medical_documents_source_id'), table_name='medical_documents')
    op.drop_index(op.f('ix_medical_documents_id'), table_name='medical_documents')
    op.drop_index(op.f('ix_medical_documents_external_id'), table_name='medical_documents')
    op.drop_table('medical_documents')
    op.drop_index(op.f('ix_medical_sources_type'), table_name='medical_sources')
    op.drop_index(op.f('ix_medical_sources_name'), table_name='medical_sources')
    op.drop_index(op.f('ix_medical_sources_id'), table_name='medical_sources')
    op.drop_table('medical_sources')
    # ### end Alembic commands ###
