"""Add MedicalAlertResult

Revision ID: 6fca01e9b941
Revises: <REVISION_GENERADA>
Create Date: 2026-09-30 18:18:46.742219

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import app


# revision identifiers, used by Alembic.
revision: str = '6fca01e9b941'
down_revision: Union[str, Sequence[str], None] = '<REVISION_GENERADA>'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('paddle_webhook_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.String(length=255), nullable=False),
    sa.Column('event_type', sa.String(length=255), nullable=False),
    sa.Column('notification_id', sa.String(length=255), nullable=True),
    sa.Column('occurred_at', sa.DateTime(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('processed', sa.Boolean(), nullable=False),
    sa.Column('processing_error', sa.String(length=1000), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_paddle_webhook_events_event_id'), 'paddle_webhook_events', ['event_id'], unique=True)
    op.create_index(op.f('ix_paddle_webhook_events_event_type'), 'paddle_webhook_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_paddle_webhook_events_id'), 'paddle_webhook_events', ['id'], unique=False)
    op.create_index(op.f('ix_paddle_webhook_events_processed'), 'paddle_webhook_events', ['processed'], unique=False)
    op.create_table('paddle_customers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('paddle_customer_id', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_paddle_customers_id'), 'paddle_customers', ['id'], unique=False)
    op.create_index(op.f('ix_paddle_customers_paddle_customer_id'), 'paddle_customers', ['paddle_customer_id'], unique=True)
    op.create_index(op.f('ix_paddle_customers_user_id'), 'paddle_customers', ['user_id'], unique=True)
    op.create_table('medical_alert_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('alert_id', sa.Integer(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('references_json', sa.Text(), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['alert_id'], ['medical_notifications.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_medical_alert_results_alert_id'), 'medical_alert_results', ['alert_id'], unique=False)
    op.create_index(op.f('ix_medical_alert_results_id'), 'medical_alert_results', ['id'], unique=False)
    op.create_table('subscriptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('plan_id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('paddle_subscription', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('period_start', sa.DateTime(), nullable=True),
    sa.Column('period_end', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['paddle_customers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['plan_id'], ['subscription_plans.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subscriptions_customer_id'), 'subscriptions', ['customer_id'], unique=False)
    op.create_index(op.f('ix_subscriptions_id'), 'subscriptions', ['id'], unique=False)
    op.create_index(op.f('ix_subscriptions_paddle_subscription'), 'subscriptions', ['paddle_subscription'], unique=True)
    op.create_index(op.f('ix_subscriptions_plan_id'), 'subscriptions', ['plan_id'], unique=False)
    op.create_index(op.f('ix_subscriptions_status'), 'subscriptions', ['status'], unique=False)
    op.create_index(op.f('ix_subscriptions_user_id'), 'subscriptions', ['user_id'], unique=False)
    op.create_table('payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('subscription_id', sa.Integer(), nullable=True),
    sa.Column('paddle_transaction', sa.String(length=255), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('paid_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['subscription_id'], ['subscriptions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payments_id'), 'payments', ['id'], unique=False)
    op.create_index(op.f('ix_payments_paddle_transaction'), 'payments', ['paddle_transaction'], unique=True)
    op.create_index(op.f('ix_payments_status'), 'payments', ['status'], unique=False)
    op.create_index(op.f('ix_payments_subscription_id'), 'payments', ['subscription_id'], unique=False)
    op.create_index(op.f('ix_payments_user_id'), 'payments', ['user_id'], unique=False)
    op.alter_column('doctor_bank_accounts', 'bank_name',
               existing_type=sa.VARCHAR(length=100),
               type_=app.core.encryption.EncryptedString(length=100),
               existing_nullable=False)
    op.alter_column('doctor_bank_accounts', 'account_number',
               existing_type=sa.VARCHAR(length=100),
               type_=app.core.encryption.EncryptedString(length=100),
               existing_nullable=False)
    op.drop_constraint(op.f('doctor_billing_profiles_doctor_id_key'), 'doctor_billing_profiles', type_='unique')
    op.create_index(op.f('ix_doctor_billing_profiles_doctor_id'), 'doctor_billing_profiles', ['doctor_id'], unique=True)
    op.create_index(op.f('ix_doctor_billing_profiles_id'), 'doctor_billing_profiles', ['id'], unique=False)
    op.create_index(op.f('ix_doctor_educations_id'), 'doctor_educations', ['id'], unique=False)
    op.drop_column('doctor_educations', 'education_type')
    op.create_index(op.f('ix_doctor_media_id'), 'doctor_media', ['id'], unique=False)
    op.alter_column('doctor_payment_settings', 'price',
               existing_type=sa.INTEGER(),
               type_=sa.Numeric(precision=12, scale=2),
               existing_nullable=False)
    op.alter_column('doctor_payment_settings', 'currency',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.String(length=3),
               existing_nullable=False)
    op.create_index(op.f('ix_doctor_reviews_id'), 'doctor_reviews', ['id'], unique=False)
    op.create_index(op.f('ix_doctor_subscriptions_id'), 'doctor_subscriptions', ['id'], unique=False)
    op.drop_column('doctors', 'bio')
    op.create_index(op.f('ix_medical_notifications_information_type'), 'medical_notifications', ['information_type'], unique=False)
    op.create_index(op.f('ix_medical_notifications_medical_topic'), 'medical_notifications', ['medical_topic'], unique=False)
    op.create_index(op.f('ix_medical_notifications_source'), 'medical_notifications', ['source'], unique=False)
    op.create_index(op.f('ix_medical_notifications_status'), 'medical_notifications', ['status'], unique=False)
    op.drop_index(op.f('ix_medical_search_usage_user_date'), table_name='medical_search_usage')
    op.drop_constraint(op.f('uq_medical_search_usage_daily'), 'medical_search_usage', type_='unique')
    op.create_index(op.f('ix_medical_search_usage_search_date'), 'medical_search_usage', ['search_date'], unique=False)
    op.create_index(op.f('ix_medical_search_usage_subscription_id'), 'medical_search_usage', ['subscription_id'], unique=False)
    op.create_index(op.f('ix_medical_search_usage_user_id'), 'medical_search_usage', ['user_id'], unique=False)
    op.create_index(op.f('ix_medical_video_calls_id'), 'medical_video_calls', ['id'], unique=False)
    op.alter_column('patients', 'gender',
               existing_type=sa.VARCHAR(length=30),
               type_=sa.String(length=50),
               existing_nullable=True)
    op.drop_index(op.f('ix_patients_document_number'), table_name='patients')
    op.drop_constraint(op.f('ck_patients_latitude_range'), 'patients', type_='check')
    op.drop_constraint(op.f('ck_patients_longitude_range'), 'patients', type_='check')
    op.drop_column('patients', 'document_type')
    op.drop_column('patients', 'latitude')
    op.drop_column('patients', 'address')
    op.drop_column('patients', 'longitude')
    op.drop_column('patients', 'document_number')
    op.create_index(op.f('ix_payments_doctor_id'), 'payments_doctor', ['id'], unique=False)
    op.create_index(op.f('ix_subscription_plans_id'), 'subscription_plans', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_subscription_plans_id'), table_name='subscription_plans')
    op.drop_index(op.f('ix_payments_doctor_id'), table_name='payments_doctor')
    op.add_column('patients', sa.Column('document_number', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.add_column('patients', sa.Column('longitude', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('patients', sa.Column('address', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('patients', sa.Column('latitude', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('patients', sa.Column('document_type', sa.VARCHAR(length=30), autoincrement=False, nullable=False))
    op.create_check_constraint(op.f('ck_patients_longitude_range'), 'patients', "longitude IS NULL OR longitude >= '-180'::integer::double precision AND longitude <= 180::double precision")
    op.create_check_constraint(op.f('ck_patients_latitude_range'), 'patients', "latitude IS NULL OR latitude >= '-90'::integer::double precision AND latitude <= 90::double precision")
    op.create_index(op.f('ix_patients_document_number'), 'patients', ['document_number'], unique=True)
    op.alter_column('patients', 'gender',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=30),
               existing_nullable=True)
    op.drop_index(op.f('ix_medical_video_calls_id'), table_name='medical_video_calls')
    op.drop_index(op.f('ix_medical_search_usage_user_id'), table_name='medical_search_usage')
    op.drop_index(op.f('ix_medical_search_usage_subscription_id'), table_name='medical_search_usage')
    op.drop_index(op.f('ix_medical_search_usage_search_date'), table_name='medical_search_usage')
    op.create_unique_constraint(op.f('uq_medical_search_usage_daily'), 'medical_search_usage', ['user_id', 'search_date'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_medical_search_usage_user_date'), 'medical_search_usage', ['user_id', 'search_date'], unique=False)
    op.drop_index(op.f('ix_medical_notifications_status'), table_name='medical_notifications')
    op.drop_index(op.f('ix_medical_notifications_source'), table_name='medical_notifications')
    op.drop_index(op.f('ix_medical_notifications_medical_topic'), table_name='medical_notifications')
    op.drop_index(op.f('ix_medical_notifications_information_type'), table_name='medical_notifications')
    op.add_column('doctors', sa.Column('bio', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_doctor_subscriptions_id'), table_name='doctor_subscriptions')
    op.drop_index(op.f('ix_doctor_reviews_id'), table_name='doctor_reviews')
    op.alter_column('doctor_payment_settings', 'currency',
               existing_type=sa.String(length=3),
               type_=sa.VARCHAR(length=10),
               existing_nullable=False)
    op.alter_column('doctor_payment_settings', 'price',
               existing_type=sa.Numeric(precision=12, scale=2),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.drop_index(op.f('ix_doctor_media_id'), table_name='doctor_media')
    op.add_column('doctor_educations', sa.Column('education_type', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_doctor_educations_id'), table_name='doctor_educations')
    op.drop_index(op.f('ix_doctor_billing_profiles_id'), table_name='doctor_billing_profiles')
    op.drop_index(op.f('ix_doctor_billing_profiles_doctor_id'), table_name='doctor_billing_profiles')
    op.create_unique_constraint(op.f('doctor_billing_profiles_doctor_id_key'), 'doctor_billing_profiles', ['doctor_id'], postgresql_nulls_not_distinct=False)
    op.alter_column('doctor_bank_accounts', 'account_number',
               existing_type=app.core.encryption.EncryptedString(length=100),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
    op.alter_column('doctor_bank_accounts', 'bank_name',
               existing_type=app.core.encryption.EncryptedString(length=100),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
    op.drop_index(op.f('ix_payments_user_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_subscription_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_status'), table_name='payments')
    op.drop_index(op.f('ix_payments_paddle_transaction'), table_name='payments')
    op.drop_index(op.f('ix_payments_id'), table_name='payments')
    op.drop_table('payments')
    op.drop_index(op.f('ix_subscriptions_user_id'), table_name='subscriptions')
    op.drop_index(op.f('ix_subscriptions_status'), table_name='subscriptions')
    op.drop_index(op.f('ix_subscriptions_plan_id'), table_name='subscriptions')
    op.drop_index(op.f('ix_subscriptions_paddle_subscription'), table_name='subscriptions')
    op.drop_index(op.f('ix_subscriptions_id'), table_name='subscriptions')
    op.drop_index(op.f('ix_subscriptions_customer_id'), table_name='subscriptions')
    op.drop_table('subscriptions')
    op.drop_index(op.f('ix_medical_alert_results_id'), table_name='medical_alert_results')
    op.drop_index(op.f('ix_medical_alert_results_alert_id'), table_name='medical_alert_results')
    op.drop_table('medical_alert_results')
    op.drop_index(op.f('ix_paddle_customers_user_id'), table_name='paddle_customers')
    op.drop_index(op.f('ix_paddle_customers_paddle_customer_id'), table_name='paddle_customers')
    op.drop_index(op.f('ix_paddle_customers_id'), table_name='paddle_customers')
    op.drop_table('paddle_customers')
    op.drop_index(op.f('ix_paddle_webhook_events_processed'), table_name='paddle_webhook_events')
    op.drop_index(op.f('ix_paddle_webhook_events_id'), table_name='paddle_webhook_events')
    op.drop_index(op.f('ix_paddle_webhook_events_event_type'), table_name='paddle_webhook_events')
    op.drop_index(op.f('ix_paddle_webhook_events_event_id'), table_name='paddle_webhook_events')
    op.drop_table('paddle_webhook_events')
    # ### end Alembic commands ###
